@extends('layouts.portal')

@section('titre', 'Catalogue de services')
@section('sous-titre', 'Accéder rapidement aux services internes de la mine')

@section('contenu')
<div class="p-6 lg:p-8 space-y-7">
    <section class="relative overflow-hidden rounded-2xl bg-[#17211f] px-6 py-8 sm:px-8 sm:py-10 text-white shadow-lg"><div class="relative z-10 max-w-2xl"><p class="text-xs font-bold uppercase tracking-[.18em] text-[#e2a05b]">Portail de services</p><h1 class="text-3xl sm:text-4xl font-bold tracking-tight mt-3">Un point d'entrée pour chaque besoin.</h1><p class="text-gray-300 mt-3 leading-relaxed">Choisissez un service, complétez les informations utiles et suivez votre demande jusqu'à sa résolution.</p><div class="flex flex-wrap gap-3 mt-6"><a href="#services" class="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-[#e2a05b] text-[#17211f] text-sm font-bold">Parcourir les services <span>↓</span></a><a href="{{ route('services.my-requests') }}" class="inline-flex items-center px-4 py-2.5 rounded-lg border border-white/20 text-white text-sm font-semibold hover:bg-white/10">Mes demandes</a></div></div><div class="absolute -right-12 -bottom-24 w-72 h-72 rounded-full border-34 border-[#b96b2c]/25"></div><div class="absolute right-16 top-12 w-20 h-20 rounded-full bg-[#176b67]/30"></div></section>

    @if($myRequests->isNotEmpty())
        <section class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden"><div class="flex items-center justify-between px-5 sm:px-6 py-5 border-b border-gray-200"><div><h2 class="font-bold text-gray-900">Vos demandes récentes</h2><p class="text-sm text-gray-500 mt-1">Un aperçu de vos dernières sollicitations.</p></div><a href="{{ route('services.my-requests') }}" class="text-sm font-semibold text-primary-700">Voir tout</a></div><div class="grid md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-gray-100">@foreach($myRequests as $request)<a href="{{ $request->ticket ? route('tickets.show', $request->ticket) : route('services.my-requests') }}" class="p-5 hover:bg-gray-50 transition"><div class="flex items-center justify-between gap-3"><span class="font-semibold text-gray-800 truncate">{{ $request->service?->name ?? 'Service' }}</span><span class="px-2.5 py-1 rounded-full text-xs font-semibold bg-gray-100 text-gray-700">{{ ucfirst($request->status) }}</span></div><p class="text-xs text-gray-500 mt-2">Soumise {{ $request->created_at->diffForHumans() }}</p></a>@endforeach</div></section>
    @endif

    <section id="services" class="space-y-7">
        @forelse($services as $categoryName => $categoryServices)
            <div><div class="flex items-end justify-between gap-3 mb-4"><div><p class="text-xs font-bold uppercase tracking-[.14em] text-primary-700">Périmètre</p><h2 class="text-xl font-bold text-gray-900 mt-1">{{ $categoryName ?? 'Services généraux' }}</h2></div><span class="text-sm text-gray-500">{{ $categoryServices->count() }} service{{ $categoryServices->count() > 1 ? 's' : '' }}</span></div><div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">@foreach($categoryServices as $service)<a href="{{ route('services.show', $service) }}" class="group bg-white border border-gray-200 rounded-xl p-5 shadow-sm hover:-translate-y-0.5 hover:border-[#b96b2c] hover:shadow-md transition"><div class="flex items-start justify-between gap-4"><span class="w-11 h-11 rounded-xl bg-[#f7eee7] text-[#8f4b1d] flex items-center justify-center"><x-icon :name="$service->icon ?? 'service'" size="md" /></span><span class="text-gray-300 group-hover:text-[#b96b2c] transition">↗</span></div><h3 class="font-bold text-gray-900 text-lg mt-5">{{ $service->name }}</h3><p class="text-sm text-gray-500 leading-relaxed mt-2 min-h-10">{{ Str::limit($service->description, 110) }}</p><div class="flex items-center justify-between gap-3 mt-5 pt-4 border-t border-gray-100 text-xs"><span class="text-gray-500">{{ $service->estimated_time ? 'Environ ' . round($service->estimated_time / 60, 1) . ' h' : 'Délai à confirmer' }}</span><span class="font-semibold {{ $service->requires_approval ? 'text-amber-700' : 'text-emerald-700' }}">{{ $service->requires_approval ? 'Approbation requise' : 'Traitement direct' }}</span></div></a>@endforeach</div></div>
        @empty
            <div class="bg-white border border-gray-200 rounded-xl p-14 text-center"><h2 class="font-bold text-gray-900">Aucun service disponible</h2><p class="text-gray-500 text-sm mt-2">Le catalogue sera alimenté par l'administrateur.</p></div>
        @endforelse
    </section>
</div>
@endsection
