@extends('layouts.portal')

@section('titre', 'Poste d’intervention')
@section('sous-titre', 'Tickets assignés, priorités et file d’attente')

@section('contenu')
<div class="p-6 lg:p-8 space-y-7">
    <section class="flex flex-col lg:flex-row lg:items-end justify-between gap-5"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-primary-700 mb-2">Opérations support</p><h1 class="text-3xl lg:text-4xl font-bold tracking-tight text-gray-900">Bonjour, {{ auth()->user()->name }}</h1><p class="text-gray-500 mt-2">Concentrez-vous sur les incidents qui ont le plus d’impact sur la mine.</p></div><a href="{{ route('kanban.index') }}" class="inline-flex items-center justify-center px-4 py-2.5 rounded-lg border border-gray-300 bg-white text-gray-700 text-sm font-semibold hover:border-primary-600 hover:text-primary-700 transition">Ouvrir le Kanban</a></section>
    <section class="grid grid-cols-2 xl:grid-cols-4 gap-3 sm:gap-4">@php($statsCards = [['label' => 'Mes tickets actifs', 'value' => $stats['mes_tickets'] ?? 0, 'tone' => 'text-blue-700'], ['label' => 'Critiques', 'value' => $stats['tickets_critiques'] ?? 0, 'tone' => 'text-red-700'], ['label' => 'À assigner', 'value' => $stats['en_attente_assignment'] ?? 0, 'tone' => 'text-amber-700'], ['label' => 'Résolus aujourd’hui', 'value' => $stats['resolus_aujourdhui'] ?? 0, 'tone' => 'text-emerald-700']])@foreach($statsCards as $item)<div class="bg-white border border-gray-200 rounded-xl px-4 py-4 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">{{ $item['label'] }}</p><p class="text-2xl font-bold {{ $item['tone'] }} mt-2">{{ number_format($item['value']) }}</p></div>@endforeach</section>
    <section class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden"><div class="flex items-center justify-between px-5 sm:px-6 py-5 border-b border-gray-200"><div><h2 class="font-bold text-gray-900">Mes tickets assignés</h2><p class="text-sm text-gray-500 mt-1">Les prochaines interventions à traiter.</p></div><a href="{{ route('tickets.index') }}" class="text-sm font-semibold text-primary-700">Voir la file</a></div>@forelse($myTickets ?? [] as $ticket)<a href="{{ route('tickets.show', $ticket) }}" class="flex items-center justify-between gap-4 px-5 sm:px-6 py-4 hover:bg-gray-50 transition"><div class="min-w-0"><div class="flex items-center gap-2"><span class="font-mono text-xs font-bold text-primary-700">{{ $ticket->reference }}</span><span class="text-xs text-gray-400">{{ $ticket->created_at?->diffForHumans() }}</span></div><p class="font-semibold text-gray-800 truncate mt-1">{{ $ticket->titre }}</p></div><span class="px-2.5 py-1 rounded-full text-xs font-semibold shrink-0" style="background:{{ $ticket->priorite?->couleur ?? '#71807b' }}18;color:{{ $ticket->priorite?->couleur ?? '#53615c' }}">{{ $ticket->priorite?->nom ?? 'Standard' }}</span></a>@empty<div class="px-6 py-14 text-center"><p class="font-semibold text-gray-800">Aucun ticket assigné.</p><p class="text-sm text-gray-500 mt-1">La file est à jour.</p></div>@endforelse</section>
</div>
@endsection
